### ISSUE TITLE
Progress-Bar slider doesn't work for the first time 

### ISSUE THREAD

**Issue by kedar2a** [cabin/videojs-sublime-skin#3]
- When we play video for first time, progress bar doesn't work as expected.
- But when first attempt has completed, it works as expected. Means we could click anywhere in progress-bar and video starts from there.
- I think, if progress bar is not working for the first time then there is no point in showing it. Or it will be good to see if it's working so.

**Comment by zakj** [comment]
Thanks for the report! I haven't had much time to maintain this lately, but will tackle it as soon as I can. PRs welcome. :)

**Comment by zakj** [comment]
@kedar2a I just release 1.0.2 which includes a fix for the vjs-poster in newer versions of video js. Please let me know if it's now working as you expect. If it's still a problem, feel free to reopen this issue, and let me know what version of video.js you're using. Thanks again!

**Comment by albricepiazza** [comment]
Hi,
i have a problem with a progress bar too.
My progress-bar doesn't work when i play a flash video.
Just, the player bug with a flash video on ie. The flash video play, but the option (play, sond, progress bar) doesn't work.
