### ISSUE TITLE
Subtitle button modification

### ISSUE THREAD

**Issue by dn5** [cabin/videojs-sublime-skin#4]
Hello,  
I can't see anywhere that the production has stopped but let me give it a try. There is no button to choose or list subtitles a/k/a `<track>` tag in HTML. Is there any possibilities for implementing one? Regards!

**Comment by zakj** [comment]
I haven't had much time lately for maintenance on this project, but I'd be happy to look at a pull request!

**Comment by dn5** [comment]
Ok. If you can point me basic steps I may do it and then push a commit request.

**Comment by zakj** [comment]
@dn5 You'd need to create an appropriate icon for the control bar, then modify the rules in `src/videojs-sublime-skin.sass` to make room for it and display it when needed. You'd also need to add styles for any subtitle menu. Closing this for now, but feel free to send a PR if you get this feature to a good place!
